apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejslab1
  labels:
    app: nodejslab1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejslab1
  template:
    metadata:
      labels:
        app: nodejslab1
    spec:
      containers:
      - name: nodejslab1
        image: sheetalsshetty/nodeexam4:latest
        ports:
        - containerPort: 3000
