apiVersion: v1
kind: Service
metadata:
  name: nodejslab
  labels:
    app: nodejslab
spec:
  type: NodePort
  selector:
    app: nodejslab
  ports:
    - port: 3008        # Service port
      targetPort: 3000  # Container port (Tomcat)
      protocol: TCP
